# Generated by Django 5.1 on 2024-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватное'),
        ),
    ]
