# Generated by Django 5.1 on 2024-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_album_is_private_alter_photo_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='access_token',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(max_length=70, verbose_name='Подпись'),
        ),
    ]
